export const TEMPLATE_CATEGORIES = [
  'geral',
  'real_estate',
  'network_marketing',
  'hospitality',
  'car_dealership',
  'politics',
  'fitness',
  'beauty',
  'tech',
  'finance',
  'healthcare',
  'education',
  'retail',
  'food',
  'services',
]

export const CATEGORY_LABELS: Record<string, string> = {
  geral: 'Geral',
  real_estate: 'Real Estate',
  network_marketing: 'Network Marketing',
  hospitality: 'Hospitalidade',
  car_dealership: 'Revendedores Auto',
  politics: 'Política',
  fitness: 'Fitness',
  beauty: 'Beleza',
  tech: 'Tecnologia',
  finance: 'Finanças',
  healthcare: 'Saúde',
  education: 'Educação',
  retail: 'Retalho',
  food: 'Alimentação',
  services: 'Serviços',
}
